### ISSUE TITLE
Improve Person links

### ISSUE THREAD

**Issue by sockeqwe** [TheContext/podcast-ci#16]
At the moment a person can have 3 links:
 - website
 - twitter
 - github

That is ok, however, if we have some time to optimize this it would be a great addition if we could make this more dynamic: Something like a `label` and `url` would be a possible solution.

i.e. Some guests don't have a website, but only a linkedin site ...

**Comment by artem-zinnatullin** [comment]
looks reasonable

**Comment by sockeqwe** [comment]
Or what about just reading it into a Map<String, String> with the key as
name that will be and always provide full URL as value

Artur Dryomov <notifications@github.com> schrieb am Di., 31. Juli 2018,
08:19:
