### ISSUE TITLE
App vs. Gradle Plugin

### ISSUE THREAD

**Issue by ming13** [TheContext/podcast-ci#2]
At this point the CI is implemented as a Gradle plugin.

I think it can be useful to use the CI as a basic Java application, i. e. `podcaster.jar` with some command line arguments. The resulting JAR can be provided via releases and downloaded using Travis.

The current Gradle plugin approach requires custom Gradle project configuration to actually do anything, if I understand correctly.

**Comment by sockeqwe** [comment]
Agreed. Will change that.

Artur Dryomov <notifications@github.com> schrieb am So., 22. Okt. 2017,
15:24:

**Comment by artem-zinnatullin** [comment]
Yep, I also prefer plain CLI tools 👍

**Comment by sockeqwe** [comment]
Closed by #4
